menubar: false

toolbar:
  - undo redo | cut copy paste | bullist numlist | outdent indent | blockquote | subscript superscript | uploadimage media link | table | hr | fullscreen
  - formatselect fontsizeselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | removeformat | code
plugins:
  - table
  - fullscreen
  - hr
  - uploadimage
  - media
  - code
  - link
relative_urls: false