DotaHero.create(id: 1, name: 'Anti-Mage', token: 'antimage')
DotaHero.create(id: 2, name: 'Axe', token: 'axe')
DotaHero.create(id: 3, name: 'Bane', token: 'bane')
DotaHero.create(id: 4, name: 'Bloodseeker', token: 'bloodseeker')
DotaHero.create(id: 5, name: 'Crystal Maiden', token: 'crystal_maiden')
DotaHero.create(id: 6, name: 'Drow Ranger', token: 'drow_ranger')
DotaHero.create(id: 7, name: 'Earthshaker', token: 'earthshaker')
DotaHero.create(id: 8, name: 'Juggernaut', token: 'juggernaut')
DotaHero.create(id: 9, name: 'Mirana', token: 'mirana')
DotaHero.create(id: 10, name: 'Morphling', token: 'morphling')
DotaHero.create(id: 11, name: 'Shadow Fiend', token: 'nevermore')
DotaHero.create(id: 12, name: 'Phantom Lancer', token: 'phantom_lancer')
DotaHero.create(id: 13, name: 'Puck', token: 'puck')
DotaHero.create(id: 14, name: 'Pudge', token: 'pudge')
DotaHero.create(id: 15, name: 'Razor', token: 'razor')
DotaHero.create(id: 16, name: 'Sand King', token: 'sand_king')
DotaHero.create(id: 17, name: 'Storm Spirit', token: 'storm_spirit')
DotaHero.create(id: 18, name: 'Sven', token: 'sven')
DotaHero.create(id: 19, name: 'Tiny', token: 'tiny')
DotaHero.create(id: 20, name: 'Vengeful Spirit', token: 'vengefulspirit')
DotaHero.create(id: 21, name: 'Windranger', token: 'windrunner')
DotaHero.create(id: 22, name: 'Zeus', token: 'zuus')
DotaHero.create(id: 23, name: 'Kunkka', token: 'kunkka')
DotaHero.create(id: 25, name: 'Lina', token: 'lina')
DotaHero.create(id: 26, name: 'Lion', token: 'lion')
DotaHero.create(id: 27, name: 'Shadow Shaman', token: 'shadow_shaman')
DotaHero.create(id: 28, name: 'Slardar', token: 'slardar')
DotaHero.create(id: 29, name: 'Tidehunter', token: 'tidehunter')
DotaHero.create(id: 30, name: 'Witch Doctor', token: 'witch_doctor')
DotaHero.create(id: 31, name: 'Lich', token: 'lich')
DotaHero.create(id: 32, name: 'Riki', token: 'riki')
DotaHero.create(id: 33, name: 'Enigma', token: 'enigma')
DotaHero.create(id: 34, name: 'Tinker', token: 'tinker')
DotaHero.create(id: 35, name: 'Sniper', token: 'sniper')
DotaHero.create(id: 36, name: 'Necrophos', token: 'necrolyte')
DotaHero.create(id: 37, name: 'Warlock', token: 'warlock')
DotaHero.create(id: 38, name: 'Beastmaster', token: 'beastmaster')
DotaHero.create(id: 39, name: 'Queen of Pain', token: 'queenofpain')
DotaHero.create(id: 40, name: 'Venomancer', token: 'venomancer')
DotaHero.create(id: 41, name: 'Faceless Void', token: 'faceless_void')
DotaHero.create(id: 42, name: 'Wraith King', token: 'skeleton_king')
DotaHero.create(id: 43, name: 'Death Prophet', token: 'death_prophet')
DotaHero.create(id: 44, name: 'Phantom Assassin', token: 'phantom_assassin')
DotaHero.create(id: 45, name: 'Pugna', token: 'pugna')
DotaHero.create(id: 46, name: 'Templar Assassin', token: 'templar_assassin')
DotaHero.create(id: 47, name: 'Viper', token: 'viper')
DotaHero.create(id: 48, name: 'Luna', token: 'luna')
DotaHero.create(id: 49, name: 'Dragon Knight', token: 'dragon_knight')
DotaHero.create(id: 50, name: 'Dazzle', token: 'dazzle')
DotaHero.create(id: 51, name: 'Clockwerk', token: 'rattletrap')
DotaHero.create(id: 52, name: 'Leshrac', token: 'leshrac')
DotaHero.create(id: 53, name: "Nature's Prophet", token: 'furion')
DotaHero.create(id: 54, name: 'Lifestealer', token: 'life_stealer')
DotaHero.create(id: 55, name: 'Dark Seer', token: 'dark_seer')
DotaHero.create(id: 56, name: 'Clinkz', token: 'clinkz')
DotaHero.create(id: 57, name: 'Omniknight', token: 'omniknight')
DotaHero.create(id: 58, name: 'Enchantress', token: 'enchantress')
DotaHero.create(id: 59, name: 'Huskar', token: 'huskar')
DotaHero.create(id: 60, name: 'Night Stalker', token: 'night_stalker')
DotaHero.create(id: 61, name: 'Broodmother', token: 'broodmother')
DotaHero.create(id: 62, name: 'Bounty Hunter', token: 'bounty_hunter')
DotaHero.create(id: 63, name: 'Weaver', token: 'weaver')
DotaHero.create(id: 64, name: 'Jakiro', token: 'jakiro')
DotaHero.create(id: 65, name: 'Batrider', token: 'batrider')
DotaHero.create(id: 66, name: 'Chen', token: 'chen')
DotaHero.create(id: 67, name: 'Spectre', token: 'spectre')
DotaHero.create(id: 68, name: 'Ancient Apparition', token: 'ancient_apparition')
DotaHero.create(id: 69, name: 'Doom', token: 'doom_bringer')
DotaHero.create(id: 70, name: 'Ursa', token: 'ursa')
DotaHero.create(id: 71, name: 'Spirit Breaker', token: 'spirit_breaker')
DotaHero.create(id: 72, name: 'Gyrocopter', token: 'gyrocopter')
DotaHero.create(id: 73, name: 'Alchemist', token: 'alchemist')
DotaHero.create(id: 74, name: 'Invoker', token: 'invoker')
DotaHero.create(id: 75, name: 'Silencer', token: 'silencer')
DotaHero.create(id: 76, name: 'Outworld Devourer', token: 'obsidian_destroyer')
DotaHero.create(id: 77, name: 'Lycan', token: 'lycan')
DotaHero.create(id: 78, name: 'Brewmaster', token: 'brewmaster')
DotaHero.create(id: 79, name: 'Shadow Demon', token: 'shadow_demon')
DotaHero.create(id: 80, name: 'Lone Druid', token: 'lone_druid')
DotaHero.create(id: 81, name: 'Chaos Knight', token: 'chaos_knight')
DotaHero.create(id: 82, name: 'Meepo', token: 'meepo')
DotaHero.create(id: 83, name: 'Treant Protector', token: 'treant')
DotaHero.create(id: 84, name: 'Ogre Magi', token: 'ogre_magi')
DotaHero.create(id: 85, name: 'Undying', token: 'undying')
DotaHero.create(id: 86, name: 'Rubick', token: 'rubick')
DotaHero.create(id: 87, name: 'Disruptor', token: 'disruptor')
DotaHero.create(id: 88, name: 'Nyx Assassin', token: 'nyx_assassin')
DotaHero.create(id: 89, name: 'Naga Siren', token: 'naga_siren')
DotaHero.create(id: 90, name: 'Keeper of the Light', token: 'keeper_of_the_light')
DotaHero.create(id: 91, name: 'Io', token: 'wisp')
DotaHero.create(id: 92, name: 'Visage', token: 'visage')
DotaHero.create(id: 93, name: 'Slark', token: 'slark')
DotaHero.create(id: 94, name: 'Medusa', token: 'medusa')
DotaHero.create(id: 95, name: 'Troll Warlord', token: 'troll_warlord')
DotaHero.create(id: 96, name: 'Centaur Warrunner', token: 'centaur')
DotaHero.create(id: 97, name: 'Magnus', token: 'magnataur')
DotaHero.create(id: 98, name: 'Timbersaw', token: 'shredder')
DotaHero.create(id: 99, name: 'Bristleback', token: 'bristleback')
DotaHero.create(id: 100, name: 'Tusk', token: 'tusk')
DotaHero.create(id: 101, name: 'Skywrath Mage', token: 'skywrath_mage')
DotaHero.create(id: 102, name: 'Abaddon', token: 'abaddon')
DotaHero.create(id: 103, name: 'Elder Titan', token: 'elder_titan')
DotaHero.create(id: 104, name: 'Legion Commander', token: 'legion_commander')
DotaHero.create(id: 105, name: 'Techies', token: 'techies')
DotaHero.create(id: 106, name: 'Ember Spirit', token: 'ember_spirit')
DotaHero.create(id: 107, name: 'Earth Spirit', token: 'earth_spirit')
DotaHero.create(id: 109, name: 'Terrorblade', token: 'terrorblade')
DotaHero.create(id: 110, name: 'Phoenix', token: 'phoenix')
DotaHero.create(id: 111, name: 'Oracle', token: 'oracle')
DotaHero.create(id: 112, name: 'Winter Wyvern', token: 'winter_wyvern')
